# Support Bandonker's Open Source Development
# Building tools for developers, funding conservation dreams

github: bandonker
patreon: Bandonker
ko_fi: bandonker
custom: ['https://www.buymeacoffee.com/Bandonker', 'https://coff.ee/bandonker']